//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarioBasico
    {
        public int IdLiquidacion { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> Salario { get; set; }
        public Nullable<int> ConceptosPositivos { get; set; }
        public Nullable<int> ConceptosNegativos { get; set; }
        public Nullable<int> Anticipo { get; set; }
        public Nullable<int> IPS { get; set; }
        public Nullable<int> TotalPercibir { get; set; }
    }
}
